version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - STACK_NAME=python-test-stack
  build:
    commands:
      - echo 'Building...'
      - echo $STACK_NAME
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --output-template-file output.yml
      - aws cloudformation deploy --template-file output.yml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM
