name: Auto Deploy Lambda on S3

on:
  push:
    branches:
      - main

env:
  base_branch: main
  diff_path: "docs/**.md"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      process.env.CI: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to S3
        run: |
          git diff --dirstat=files,0 origin/main...HEAD
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1
