name: Auto Deploy Lambda on S3

on:
  push:
    branches:
      - main

env:
  base_branch: main
  diff_path: "docs/**.md"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      process.env.CI: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}

      - name: Deploy to S3
        run: |
          diff_files=$(git diff --name-only HEAD ${base_branch} -- "${diff_path}" | tr "\n" " ")
          echo "# diff_files: ${diff_files}"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-1
